Repository lbryio/lbry-docker, pull requests merged in 2019-04, with the labels that each got.

#47 Adds new multi-stage Dockerfile for lbrycrd and mountable config files.
  lbrycrd/Dockerfile
  lbrycrd/stuff/fix-permissions.c
  lbrycrd/stuff/start.sh
Labels: Accepted, enhancement

#48 Adds cloud-init systemd HOWTO for lbrycrd on DigitalOcean.
  contrib/lbrycrd-cloud-init.md
Labels: Accepted, enhancement

#68 Graceful stopping is critical in Chainquery
  chainquery/Dockerfile-linux-x86_64-production
Labels: priority: high, type: improvement, type: testing

#67 Adding and enabling HEALTHCHECK
  chainquery/Dockerfile-linux-x86_64-production
  chainquery/stuff/healthcheck.sh
Labels: help wanted, priority: low, type: improvement, type: refactor, type: testing
